version: '3.9'
services:
  app:
    build: .
    ports:
      - 8080:8080
  
  frontendapp:
    depends_on:
      - app
    build:
      context: ./frontend
    ports:
      - 6000:6000
    # volumes:
      # - /frontend:/frontend